"""Export the trained Random Forest to standalone C for on-device inference
(e.g. Jetson Nano), via m2cgen.

The generated code has no runtime dependencies (no Python, no libc beyond
<string.h>) -- just plain C, so it can be compiled directly into
jcparallelbench or any other C caller. This is preferred over shipping the
joblib/pickle file to the device: pickle requires a matching Python +
numpy/scipy/scikit-learn stack on-device and is fragile across library
version mismatches, neither of which is appealing on a resource-constrained
board.

This exports the *classifier* only. The 9 features it expects
(extract_features.FEATURE_NAMES) are computed in Python here
(Pillow/numpy/scipy) but have a separate, independent C port for on-device
use: src/jcfeatures.c (see its header comment for fidelity caveats --
it's a close but not bit-exact port).
"""

import argparse
from pathlib import Path

import joblib
import m2cgen


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bench-dir", type=Path, default=Path("../../bench_results"))
    parser.add_argument(
        "--model-path", type=Path, default=None, help="defaults to <bench-dir>/complexity_model.joblib"
    )
    parser.add_argument(
        "--out", type=Path, default=None, help="defaults to <bench-dir>/complexity_model.c"
    )
    args = parser.parse_args()

    model_path = args.model_path or args.bench_dir / "complexity_model.joblib"
    out_path = args.out or args.bench_dir / "complexity_model.c"

    bundle = joblib.load(model_path)
    model, feature_names = bundle["model"], bundle["feature_names"]

    body = m2cgen.export_to_c(model)

    header_comment = "\n".join(
        [
            "/*",
            " * Auto-generated by scripts/ml/export_c_model.py -- do not edit by hand.",
            " * Re-run after retraining (train_model.py) to regenerate.",
            " *",
            " * score(input, output):",
            " *   input:  array of %d features, IN THIS EXACT ORDER:" % len(feature_names),
            *(f" *     input[{i}] = {name}" for i, name in enumerate(feature_names)),
            " *   output: array of 2 doubles, class probabilities:",
            " *     output[0] = P(simple), output[1] = P(complex)",
            " *   Predicted label = argmax(output) (0=simple, 1=complex).",
            " *",
            " * Features must be computed exactly as in scripts/ml/extract_features.py",
            " * -- see src/jcfeatures.c for the C port (jcfeat_extract()).",
            " */",
            "",
        ]
    )

    out_path.write_text(header_comment + body)
    node_count = sum(t.tree_.node_count for t in model.estimators_)
    print(
        f"exported {len(model.estimators_)} trees ({node_count} nodes) "
        f"-> {out_path} ({out_path.stat().st_size / 1024:.1f} KB)"
    )


if __name__ == "__main__":
    main()
