/*
 * jcadaptive.c
 *
 * Adaptive-core JPEG encoder: loads one image, extracts the same 9
 * pre-encode features used to train the complexity classifier
 * (jcfeatures.c / scripts/ml/extract_features.py), runs the classifier
 * (complexity_model.c, generated by scripts/ml/export_c_model.py) to
 * predict "simple" or "complex", picks a core count accordingly (2 cores
 * for simple, 4 for complex), and encodes the image with the strip-
 * parallel encoder (jcparallel.c), splicing the strips into a single
 * output JPEG.
 *
 * Usage: jcadaptive-static <input-image> <output.jpg>
 *          [-quality Q] [-threads N]
 *   -quality Q   JPEG quality, 0-100 (default 85)
 *   -threads N   override the classifier and force this thread/core count
 *                (for comparison -- normal use lets the classifier decide)
 *
 * Supported input formats: same as jcparallelbench (JPEG 8-bit, BMP, PNG,
 * PPM/PGM), via jcimageload.c.
 *
 * For conditions of distribution and use, see the accompanying README.ijg
 * file.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "jcfeatures.h"
#include "jcimageload.h"
#include "jcmodel.h"
#include "jcparallel.h"
#include "jpeglib.h"

#define DEFAULT_QUALITY  85
#define SIMPLE_THREADS   2
#define COMPLEX_THREADS  4

static unsigned long file_size(const char *path) {
  struct stat st;

  if (stat(path, &st) != 0)
    return 0;
  return (unsigned long)st.st_size;
}

static void usage(const char *progname) {
  fprintf(stderr,
          "Usage: %s <input-image> <output.jpg> [-quality Q] [-threads N]\n"
          "  -quality Q   JPEG quality, 0-100 (default %d)\n"
          "  -threads N   override the classifier, force this core count\n",
          progname, DEFAULT_QUALITY);
}

int main(int argc, char **argv) {
  const char *in_path = NULL, *out_path = NULL;
  int quality = DEFAULT_QUALITY, forced_threads = -1, threads;
  jcil_loaded_image img;
  double features[JCFEAT_NUM_FEATURES];
  double proba[2];
  int predicted_label, max_v_samp_factor, num_strips = 0;
  unsigned char *jpeg_buf = NULL;
  unsigned long jpeg_size = 0;
  FILE *out;
  int i;

  for (i = 1; i < argc; i++) {
    if (strcmp(argv[i], "-quality") == 0 && i + 1 < argc) {
      quality = atoi(argv[++i]);
    } else if (strcmp(argv[i], "-threads") == 0 && i + 1 < argc) {
      forced_threads = atoi(argv[++i]);
    } else if (!in_path) {
      in_path = argv[i];
    } else if (!out_path) {
      out_path = argv[i];
    } else {
      usage(argv[0]);
      return 2;
    }
  }

  if (!in_path || !out_path) {
    usage(argv[0]);
    return 2;
  }

  if (!jcil_load_image(in_path, &img)) {
    fprintf(stderr, "%s: failed to load (unsupported or unreadable)\n",
            in_path);
    return 1;
  }

  jcfeat_extract(img.rows, img.width, img.height, img.components,
                 file_size(in_path), features);
  score(features, proba);
  predicted_label = (proba[1] > proba[0]) ? 1 : 0;

  threads = (forced_threads > 0)
                ? forced_threads
                : (predicted_label == 0 ? SIMPLE_THREADS : COMPLEX_THREADS);

  fprintf(stderr,
          "%s: %ux%u, predicted %s (P(simple)=%.3f P(complex)=%.3f) -> "
          "%d core%s%s\n",
          in_path, (unsigned)img.width, (unsigned)img.height,
          predicted_label == 0 ? "simple" : "complex", proba[0], proba[1],
          threads, threads == 1 ? "" : "s",
          forced_threads > 0 ? " (forced)" : "");

  max_v_samp_factor =
      jcil_get_max_v_samp_factor(img.color_space, img.components);

  if (!jpar_encode_strips_spliced(img.rows, img.width, img.height,
                                   max_v_samp_factor, img.components,
                                   img.color_space, quality, threads,
                                   &jpeg_buf, &jpeg_size, &num_strips)) {
    fprintf(stderr, "%s: adaptive encode failed\n", in_path);
    jcil_free_loaded_image(&img);
    return 1;
  }

  out = fopen(out_path, "wb");
  if (!out || fwrite(jpeg_buf, 1, jpeg_size, out) != jpeg_size) {
    fprintf(stderr, "%s: failed to write output\n", out_path);
    if (out)
      fclose(out);
    free(jpeg_buf);
    jcil_free_loaded_image(&img);
    return 1;
  }
  fclose(out);

  fprintf(stderr, "%s: wrote %lu bytes (%d strips spliced, %d cores)\n",
          out_path, jpeg_size, num_strips, threads);

  free(jpeg_buf);
  jcil_free_loaded_image(&img);
  return 0;
}
