/*
 * jcmodel.h
 *
 * Declares the score() function generated by scripts/ml/export_c_model.py
 * (via m2cgen) into complexity_model.c -- the trained Random Forest
 * complexity classifier.  See scripts/ml/README.md for how it was trained
 * and exported.
 *
 * After retraining, regenerate with:
 *   cd scripts/ml && uv run export_c_model.py --out ../../src/complexity_model.c
 * complexity_model.c is committed to the repo (unlike scripts/ml/'s other
 * outputs under bench_results/, which are gitignored) since it's a build
 * input for jcadaptive-static, not something regenerated by the CMake
 * build itself.
 *
 * For conditions of distribution and use, see the accompanying README.ijg
 * file.
 */

#ifndef JCMODEL_H
#define JCMODEL_H

/*
 * input:  JCFEAT_NUM_FEATURES (9) doubles, in the exact order
 *         jcfeat_extract() (jcfeatures.h) produces them.
 * output: 2 doubles, class probabilities: output[0] = P(simple),
 *         output[1] = P(complex).  Predicted label = argmax(output),
 *         i.e. output[1] > output[0] means "complex".
 */
void score(double *input, double *output);

#endif /* JCMODEL_H */
